@startuml
package "Host OS" {
  node "Vagrant" {
    [Ubuntu] as VM
  }
  [bootstrap]
  [vagrant_data]
  [VagrantFile]
  Vagrant -left-> vagrant_data
  Vagrant -down-> ExposedPorts
  note right of bootstrap: Shell Provisioner
  note top of Vagrant: Provisioned on VirtualBox
  note right of vagrant_data
    Shared storage between
    host and vm
  end note
}
@enduml
